Support passing a Windows path to `VirtualEnv.create`
Calling `virtualenv.create('C:\\Python310\\python.exe')` would fail with

    RuntimeError: failed to find interpreter for Builtin discover of
    python_spec='C:Python310python.exe'

`sh` works fine with paths of the form `C:/Python310/python.exe`, so we
replace backslashes with forward slashes on Windows.